apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
data:
  VAULT_URL: {{ required "Value for .settings.vault_url is required and should point to your vault endpoint" .Values.unsealer.vault_url}}
  VAULT_ROOT_TOKEN_SECRET: {{ .Values.unsealer.vault_root_token_secret }}
  VAULT_KEYS_SECRET: {{ .Values.unsealer.vault_keys_secret }}