kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-unsealer.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-unsealer.fullname" . }}